const questions = [
    "Never have I ever cheated on a test.",
    "Never have I ever sent a text to the wrong person.",
    "Never have I ever laughed at a funeral.",
    "Never have I ever lied about my age.",
    "Never have I ever walked into a glass door.",
    "Never have I ever waved at someone who wasn't waving at me.",
    "Never have I ever called a teacher 'Mom'.",
    "Never have I ever forgotten someone's name immediately after meeting them.",
    "Never have I ever sent a screenshot of a conversation to the person I was talking to.",
    "Never have I ever worn a shirt inside out all day.",
    "Never have I ever accidentally walked into the wrong restroom.",
    "Never have I ever tried to push a door that said 'pull'.",
    "Never have I ever fallen asleep in class.",
    "Never have I ever eaten food that fell on the floor.",
    "Never have I ever pretended to know a stranger.",
    "Never have I ever forgotten to mute myself on a video call.",
    "Never have I ever danced in public when I thought no one was watching.",
    "Never have I ever fallen out of bed while sleeping.",
    "Never have I ever liked an old photo by accident while stalking.",
    "Never have I ever pretended to be on the phone to avoid someone.",
    "Never have I ever used someone else's Netflix password.",
    "Never have I ever tried to guess someone's password.",
    "Never have I ever ignored a text for days and then replied 'Sorry, just saw this'.",
    "Never have I ever unlisted a photo because it didn't get enough likes.",
    "Never have I ever forgotten to take my phone out of my pocket before washing my clothes.",
    "Never have I ever pretended to be sick to avoid plans.",
    "Never have I ever replied 'lol' without actually laughing.",
    "Never have I ever forgotten why I walked into a room.",
    "Never have I ever pretended to understand something when I didn’t.",
    "Never have I ever said 'you too' when it made no sense.",
    "Never have I ever judged someone by their music taste.",
    "Never have I ever overthought a short reply.",
    "Never have I ever Googled something and immediately felt stupid.",
    "Never have I ever doubted my own worth.",
    "Never have I ever blamed myself for something that wasn’t my fault.",
    "Never have I ever hurt someone’s feelings and acted like it was nothing.",
    "Never have I ever felt like I wasn’t good enough.",
    "Never have I ever compared myself to others and felt inferior.",
    "Never have I ever struggled to accept compliments.",
    "Never have I ever felt lonely in a crowd.",
    "Never have I ever been afraid to express my true feelings.",
    "Never have I ever felt like I was pretending to be someone I’m not.",
    "Never have I ever felt like I was invisible to others.",
    "Never have I ever doubted my abilities.",
    "Never have I ever felt like I didn’t belong.",
];

function nextQuestion() {
    const display = document.getElementById("question-area");
    const randomIndex = Math.floor(Math.random() * questions.length);
    display.innerText = questions[randomIndex];
}